### ISSUE TITLE
求职AI金融产品经理

### ISSUE THREAD

**Issue by StevenJokess** [terrytangyuan/distributed-ml-patterns#1]
失业600天，求职AI金融产品经理
- 金融方面：2020届的山西大学金融学专业的毕业生，获得三好学生&学业奖学金，拥有会计、证券、基金从业证书，毕业论文是用Python的Statsmodel库里的VAR模型完成的《中美股市的联动性分析》，提出百度股价被低估能上300USD的想法，实现后。现注意到百度股票主打AI第一股重新去香港上市。
- AI方面：我的整个经历，大一参加数学建模了解了神经网络算法，后在网络金融课分享了鱼书的ppt，得知金融方面的非结构信息常用深度学习算法，之后阅读过二十几本人工智能相关书籍，在20年用4个月自学完了《动手学深度学习》预览版并动手翻译了GAN从MXNet到PyTorch&TF2;DCGAN从MXNet到PyTorch，复现PyTorch、DJL等一系列深度学习移动端框架的Demo。
- 产品经理方面：虽然没有工作经历，但还是努力修炼了一系列的能力。战略能力上，在百度一面失败后，考虑到了百度开发者版的想法。沟通能力上，与MXNet的开发者交流无人社区冷淡情况。学习上，学习十余本产品有关的书，并自行总结了AI产品经理的工作内容和技能要求，用Docker部署成《To be AI PM》书。

简历更多，见https://stevenjokess.github.io/2bPM/get_started.html

**Comment by StevenJokess** [comment]
为什么不用类似d2lbook的模式写这本书？

**Comment by terrytangyuan** [comment]
This is not an appropriate place to discuss your personal career development.

**Comment by StevenJokess** [comment]
@terrytangyuan You only care about yourself. I'm not discussing my career. I'm trying surviving.
